%% Using the GA on the Kuramoto oscillator data
% 
%       730 sec (10k competitions)
%
% Billy McDermot, July 2022
rng(1)
close all;
clc;

%% Load kuramoto data

data = load('Data\Kuramoto\8x32_10000.mat');    % phases generated by gauss_vs_discrete.m with 1000 points
phase = data.phase;

%% use GA to find causally emergent V

[bw, bf, mf, sf] = simulateGA({phase}, 100, 5, 100000, 0.3, 0.8);

%% plots
plot(bf, 'LineWidth', 2)
hold on
plot([0 100000],[0 0], '--black')
xlabel('GA Competitions')
ylabel('Fitness / Psi')
ylim([-0.1, 0.01])
