%% Using Kuramoto Oscillator data to compare Gaussian vs discrete CE values
% 
%       We use the GA on the MEG data X to find causally emergent V. We
%       then discretise this into 2-5 levels and compute Psi using discrete
%       MI.
%
%   100k GA iterations, 100 pop, 5 deme (20 mins, Psi = 0.7)
%   100k GA iterations, 500 pop, 25 deme (18 mins, Psi = 0.5)
%   100k GA iterations, 200 pop, 10 deme (18 mins, Psi = 0.7)
%
%   Billy McDermot, July 2022
rng(1)
close all;
clc;

%% Load MEG data

data = load('Data\Psychedelics\KET\021013_51_KET.mat');    % phases generated by gauss_vs_discrete.m with 1000 points
data = cell2mat(data.dat);
% only use the first 6000 steps (10 seconds of data)
X = data(:,1:6000);

% find shape of data
D = length(data(:,1));
T = length(data);

%% use GA to find causally emergent V

[bw, bf, mf, sf] = simulateGA({X}, 200, 10, 100000, 0.3, 0.8, 'min');

%% calculate V for entire time series and calculate psi

V = sum(data.*bw.');
gauss_psi = EmergencePsi(data.', V);

%% discretise X and V and calculate psi

% discretise X and V
bins = [2:5];
disc_Xs = zeros(length(bins), T, D);
disc_Vs = zeros(length(bins), 1, T);

for i = 1:length(bins)
    disc_Xs(i,:,:) = discretise(data.', bins(i));
    disc_Vs(i,:,:) = discretise(V, bins(i));
end

% calculate discrete psi
disc_psi = zeros(length(bins));

for i = 1:length(bins)
    for j = 1:length(bins)
        disc_psi(i, j) = EmergencePsi(reshape(disc_Xs(i,:,:),T,D), reshape(disc_Vs(j,:,:),1,T));
    end
end

%% plot
figure(1)
plot(bf)

figure(2)
plot(bw)

% create custom colormap
map1 = [linspace(0,1,64)', linspace(0,1,64)', linspace(1,1,64)'];
map2 = [linspace(1,0,64)', linspace(1,1,64)', linspace(1,0,64)'];
map = vertcat(map1,map2);

% discrete psis
figure(3)
heatmap(bins, bins, disc_psi)
caxis([gauss_psi - 0.5, gauss_psi + 0.5])
colormap(map)
xlabel('V levels')
ylabel('X levels')