%% Using Kuramoto Oscillator data to compare Gaussian vs discrete CE values
% 
%       We use the phases generated by a Kuramoto oscillator (which are
%       uniformly distributed) and map them to be normally distributed. We
%       then use the GA to find a causally emergent function to form the
%       macrovariable V and compare the Psi values calculated using the
%       Gaussian approximation against a discretisation.
%
% Billy McDermot, July 2022
rng(1)
close all;
clc;

%% Load kuramoto data

data = load('Data\Kuramoto\8x32_10000.mat');    % phases generated by gauss_vs_discrete.m with 1000 points
phase = data.phase;

%% convert phase to be uniform

X = uniform2gaussian(phase, -pi, pi, 0, 1);
X = {X};

%% use GA to find causally emergent V

[bw, bf, mf, sf] = simulateGA(X, 100, 5, 10000, 0.3, 0.8, 'mean');